config/routes.rb
Rails.application.routes.draw do
  resources :movies 
  root 'pages#home'
  get "/nome", to: "pages#nome"
  get "/home", to: "pages#home"
  get "/fome", to: "pages#fome"
  get "/draw", to: "pages#draw"
  get "/sketch", to: "pages#sketch"
  get "/complete", to: "pages#complete"
  get "/vaulted", to: "pages#vaulted"
  devise_for :users
 
  resources :suggestions do
    member do
      post "like" => "suggestions#like"
      post 'change_box' => "suggestions#change_box" 
      post 'show_description' => 'suggestions#description'
      post 'back' => 'suggestions#back'
    end
  end

  resources :suggestions do
    collection do
      post 'clear' 
    end
  end

  resources :movies do
    resources :reviews
  end


  resources :posts,:suggestions, :screenings, :reviews, :sugg_boxes
end

app/models/screening.rb
class Screening < ApplicationRecord
end

app/controllers/screenings_controller.rb
class ScreeningsController < ApplicationController
  before_action :set_screening, only: %i[ show edit update destroy ]

  # GET /screenings or /screenings.json
  def index
    @screenings = Screening.all
  end

  # GET /screenings/1 or /screenings/1.json
  def show
  end

  # GET /screenings/new
  def new
    @screening = Screening.new
  end

  # GET /screenings/1/edit
  def edit
  end

  # POST /screenings or /screenings.json
  def create
    @screening = Screening.new(screening_params)

    respond_to do |format|
      if @screening.save
        format.html { redirect_to screening_url(@screening), notice: "Screening was successfully created." }
        format.json { render :show, status: :created, location: @screening }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @screening.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /screenings/1 or /screenings/1.json
  def update
    respond_to do |format|
      if @screening.update(screening_params)
        format.html { redirect_to screening_url(@screening), notice: "Screening was successfully updated." }
        format.json { render :show, status: :ok, location: @screening }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @screening.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /screenings/1 or /screenings/1.json
  def destroy
    @screening.destroy

    respond_to do |format|
      format.html { redirect_to screenings_url, notice: "Screening was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_screening
      @screening = Screening.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def screening_params
      params.require(:screening).permit(:title, :description, :start_time, :end_time)
    end
end

app/helpers/screenings_helper.rb
module ScreeningsHelper
end

app/views/screenings/_form.html.erb
<%= form_with(model: screening, class: "contents") do |form| %>
  <% if screening.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(screening.errors.count, "error") %> prohibited this screening from being saved:</h2>

      <ul>
        <% screening.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :start_time %>
    <%= form.datetime_field :start_time, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :end_time %>
    <%= form.datetime_field :end_time, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/screenings/_screening.html.erb
<div id="<%= dom_id screening %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= screening.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= screening.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Start time:</strong>
    <%= screening.start_time %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">End time:</strong>
    <%= screening.end_time %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this screening", screening, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this screening', edit_screening_path(screening), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/screenings/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing screening</h1>

  <%= render "form", screening: @screening %>

  <%= link_to "Show this screening", @screening, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to screenings", screenings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/screenings/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Screenings</h1>
    <%= link_to 'New screening', new_screening_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="screenings" class="min-w-full">
    <%= render @screenings %>
  </div>

  <div class="containter mt-5 text-center">
    <h1> This is sample content</h1>
    <p> ... </p>
    <%= month_calendar(events: @screenings) do |date| %>
      <div class="day">
        <%= date.day %>
      </div>
    <% end %>
  </div>

</div>

app/views/screenings/new.html.erb
<div class="container">
  <div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">New screening</h1>

    <%= render "form", screening: @screening %>

    <%= link_to 'Back to screenings', screenings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/screenings/not_home.html.erb
<div class="containter mt-5 text-center">
  <h1> This is sample content</h1>
  <p> ... </p>
  <%= month_calendar(events: @screenings) do |date| %>
    <div class="day">
      <%= date.day %>
    </div>
  <% end %>
</div>

app/views/screenings/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @screening %>

    <%= link_to 'Edit this screening', edit_screening_path(@screening), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this screening', screening_path(@screening), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to screenings', screenings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>