config/routes.rb
Rails.application.routes.draw do
  resources :movies 
  root 'pages#home'
  get "/nome", to: "pages#nome"
  get "/home", to: "pages#home"
  get "/fome", to: "pages#fome"
  get "/draw", to: "pages#draw"
  get "/sketch", to: "pages#sketch"
  get "/complete", to: "pages#complete"
  get "/vaulted", to: "pages#vaulted"
  devise_for :users
 
  resources :suggestions do
    member do
      post "like" => "suggestions#like"
      post 'change_box' => "suggestions#change_box" 
      post 'show_description' => 'suggestions#description'
      post 'back' => 'suggestions#back'
    end
  end

  resources :suggestions do
    collection do
      post 'clear' 
    end
  end

  resources :movies do
    resources :reviews
  end


  resources :posts,:suggestions, :screenings, :reviews, :sugg_boxes
end

app/models/sugg_box.rb
class SuggBox < ApplicationRecord
  has_many :suggestions
  validates :name, presence: true
end

app/controllers/sugg_boxes_controller.rb
class SuggBoxesController < ApplicationController
  before_action :set_sugg_box, only: %i[ show edit update destroy ]

  # GET /sugg_boxes or /sugg_boxes.json
  def index
    @sugg_boxes = SuggBox.all
  end

  # GET /sugg_boxes/1 or /sugg_boxes/1.json
  def show
  end

  # GET /sugg_boxes/new
  def new
    @sugg_box = SuggBox.new
  end

  # GET /sugg_boxes/1/edit
  def edit
  end

  # POST /sugg_boxes or /sugg_boxes.json
  def create
    @sugg_box = SuggBox.new(sugg_box_params)

    respond_to do |format|
      if @sugg_box.save
        format.html { redirect_to sugg_box_url(@sugg_box), notice: "Sugg box was successfully created." }
        format.json { render :show, status: :created, location: @sugg_box }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sugg_box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sugg_boxes/1 or /sugg_boxes/1.json
  def update
    respond_to do |format|
      if @sugg_box.update(sugg_box_params)
        format.html { redirect_to sugg_box_url(@sugg_box), notice: "Sugg box was successfully updated." }
        format.json { render :show, status: :ok, location: @sugg_box }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sugg_box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sugg_boxes/1 or /sugg_boxes/1.json
  def destroy
    @sugg_box.destroy

    respond_to do |format|
      format.html { redirect_to sugg_boxes_url, notice: "Sugg box was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sugg_box
      @sugg_box = SuggBox.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sugg_box_params
      params.require(:sugg_box).permit(:name)
    end
end

app/helpers/sugg_boxes_helper.rb
module SuggBoxesHelper
end

app/views/sugg_boxes/_form.html.erb
<%= form_with(model: sugg_box, class: "contents") do |form| %>
  <% if sugg_box.errors.any? %>
    <div id="error_explanation" class="px-3 py-2 mt-3 font-medium text-red-500 rounded-lg bg-red-50">
      <h2><%= pluralize(sugg_box.errors.count, "error") %> prohibited this sugg_box from being saved:</h2>

      <ul>
        <% sugg_box.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name, class:"field text-sky-200" %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/sugg_boxes/_sugg_box.html.erb
<div id="<%= dom_id sugg_box %>", class="text-white">
  <% if action_name != "show" %>
    <%= link_to "Show this sugg box", sugg_box, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this sugg box', edit_sugg_box_path(sugg_box), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
  <p><%= @sugg_boxes.map(&:name)%></p>
  <p><%= @sugg_boxes.collect {|n| n.name}%></p>
  <p><%= @sugg_boxes.name%></p>
  <p><%= instance_variable_names.inspect %></p>
</div>

app/views/sugg_boxes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing sugg box</h1>

  <%= render "form", sugg_box: @sugg_box %>

  <%= link_to "Show this sugg box", @sugg_box, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to sugg boxes", sugg_boxes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/sugg_boxes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="inline-block px-3 py-2 mb-5 font-medium text-green-500 rounded-lg bg-green-50" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex items-center justify-between">
    <h1 class="text-4xl font-bold">Sugg boxes</h1>
    <%= link_to 'New sugg box', new_sugg_box_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="sugg_boxes" class="min-w-full">
    <%= render @sugg_boxes %>
  </div>

  <p>
    <% @sugg_boxes.each do |s| %>
      <%= s.name %>
    <% end %>
  </p>
</div>

app/views/sugg_boxes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New sugg box</h1>

  <%= render "form", sugg_box: @sugg_box %>

  <%= link_to 'Back to sugg boxes', sugg_boxes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/sugg_boxes/show.html.erb
<div class="flex w-full mx-auto md:w-2/3">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="inline-block px-3 py-2 mb-5 font-medium text-green-500 rounded-lg bg-green-50" id="notice"><%= notice %></p>
    <% end %>

    <%= render @sugg_box %>

    <%= link_to 'Edit this sugg_box', edit_sugg_box_path(@sugg_box), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this sugg_box', sugg_box_path(@sugg_box), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to sugg_boxes', sugg_boxes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>