config/routes.rb
Rails.application.routes.draw do
  resources :movies 
  root 'pages#home'
  get "/nome", to: "pages#nome"
  get "/home", to: "pages#home"
  get "/fome", to: "pages#fome"
  get "/draw", to: "pages#draw"
  get "/sketch", to: "pages#sketch"
  get "/complete", to: "pages#complete"
  get "/vaulted", to: "pages#vaulted"
  devise_for :users
 
  resources :suggestions do
    member do
      post "like" => "suggestions#like"
      post 'change_box' => "suggestions#change_box" 
      post 'show_description' => 'suggestions#description'
      post 'back' => 'suggestions#back'
    end
  end

  resources :suggestions do
    collection do
      post 'clear' 
    end
  end

  resources :movies do
    resources :reviews
  end


  resources :posts,:suggestions, :screenings, :reviews, :sugg_boxes
end

app/views/shared/_nav_bar.html.erb
  <div class="pt-5 mb-10">
    <nav class="flex flex-wrap items-center justify-between p-3 rounded-md bg-fuchsia-900">
      <div class="flex items-center flex-shrink-0 mr-6 text-rose-50">
        <%# <svg class="w-8 h-8 mr-2 fill-current" width="54" height="54" viewBox="0 0 54 54" image href="signature.jpg"></svg> %>
        <span class="text-xl font-semibold tracking-tight text-red-200">Movie Night 🍿</span>
      </div>
      <div class="flex-grow block w-full text-sm text-red-200 lg:flex lg:items-center lg:w-auto ">
        <div class="lg:flex-grow">
          <a href="#responsive-header" >
            <%= link_to "Home", home_path, class: "block mt-1 mr-4 text-teal-200 lg:inline-block lg:mt-0 font-serif text-base hover:text-white" %>
          </a>
          <a href="#responsive-header" >
            <%= link_to "Suggestions", new_suggestion_path, class:"block mt-1 mr-4 text-teal-200 lg:inline-block lg:mt-0 font-serif text-base hover:text-white" %>
          <a href="#responsive-header" >
            <%= link_to "Movies", movies_path, class: "block mt-1 mr-4 text-teal-200 lg:inline-block lg:mt-0 font-serif text-base hover:text-white" %>
          </a>
          </a>
          <a href="#responsive-header" >
            <%= link_to "Reviews", fome_path, class: "block mt-1 mr-4 text-teal-200 lg:inline-block lg:mt-0 font-serif text-base hover:text-white" %>
          </a>
        </div>
        <div>
          <% if !user_signed_in? %>
            <a href="#responsive-header" >
              <%= link_to "Login", new_user_session_path, class: "block mt-1 mr-4 text-teal-200 md:mr-16 lg:inline-block lg:mt-0 font-serif text-base hover:text-white" %>
            </a>
          <% else %>
            <a href="#responsive-header" >
              <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete, class: "block mt-1 mr-4 text-teal-200 md:mr-16 lg:inline-block lg:mt-0 font-serif text-base hover:text-white" %>
            </a>
          <% end %>
        </div>
      </div>
    </nav>
  </div>