config/routes.rb
Rails.application.routes.draw do
  resources :movies 
  root 'pages#home'
  get "/nome", to: "pages#nome"
  get "/home", to: "pages#home"
  get "/fome", to: "pages#fome"
  get "/draw", to: "pages#draw"
  get "/sketch", to: "pages#sketch"
  get "/complete", to: "pages#complete"
  get "/vaulted", to: "pages#vaulted"
  devise_for :users
 
  resources :suggestions do
    member do
      post "like" => "suggestions#like"
      post 'change_box' => "suggestions#change_box" 
      post 'show_description' => 'suggestions#description'
      post 'back' => 'suggestions#back'
    end
  end

  resources :suggestions do
    collection do
      post 'clear' 
    end
  end

  resources :movies do
    resources :reviews
  end


  resources :posts,:suggestions, :screenings, :reviews, :sugg_boxes
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
  acts_as_votable
  validates :movie, presence: true
  validates :author, presence: true
  belongs_to :sugg_box

  # def initialize
  #   self.add_quick_description
  # end

  def self.move_old_weekly_suggestions
    seconds_in_a_week = 345_600 
    t = Time.now
    suggestions = SuggBox.find_by_name("Weekly").suggestions.all
    suggestions.each do |s|
      if t - s.updated_at > seconds_in_a_week
        s.move_suggestions_to_new_box(SuggBox.find_by_name("All Encompassing").id)
      end
    end
  end

  def move_suggestions_to_new_box(destination_box_id)
    self.update(sugg_box_id: destination_box_id)
    self.get_likes.delete_all
  end

  def add_quick_description
    agent = Mechanize.new
    agent.log = Logger.new 'mech.log'
    agent.user_agent_alias = 'Linux Firefox'
    page = agent.get('https://www.imdb.com/')

    # nav and search
    imdb_search_form = page.form('nav-search-form')
    imdb_search_form.q = "#{self.movie}"

    # collect links and get uri of first result
    page = agent.submit(imdb_search_form, imdb_search_form.buttons.first)
    options = agent.page.links

    first_option = options.find do |link|
      link.resolved_uri.to_s.include?('fn_al_tt_1')
    end.resolved_uri

    # get description off page
    description = agent.get(first_option).search(".//span[@class='sc-2d37a7c7-0 ftDfUj']").text
    self.description = description
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  helper_method :change_box

  def index
    @suggestions = Suggestion.all
  end

  def show
    @suggestion = Suggestion.find(params[:id])
    @movie = @suggestion.movie
  end

  def new
    @sugg_boxes = SuggBox.all
    @suggestion = Suggestion.new
    @suggestions = Suggestion.all
    @weekly_suggestions = @sugg_boxes.find_by_name("Weekly").suggestions
    @all_time_minus_weekly_suggestions = @sugg_boxes.find_by_name("All Encompassing").suggestions
    @recent_movie = Movie.last
    @review = Review.new
    @movie = Movie.last
  end

  def create
    @suggestion = Suggestion.new(suggestion_params) do |s|
      id = SuggBox.find_by_name("Weekly").id
      s.sugg_box_id = id
      s.add_quick_description
    end
    if @suggestion.save
      redirect_to new_suggestion_path, status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def change_box
    @suggestion = Suggestion.find(params[:id])
    if @suggestion.sugg_box.name == "All Encompassing" 
      destination_box_id = SuggBox.find_by_name("Weekly").id
    elsif @suggestion.sugg_box.name == "Weekly"
      destination_box_id = SuggBox.find_by_name("All Encompassing").id
    end
    @suggestion.move_suggestions_to_new_box(destination_box_id)
    redirect_to new_suggestion_path, status: :see_other
  end

  def destroy
    @Suggestion = Suggestion.find(params[:id])
    if current_user.email == @Suggestion.user
      @Suggestion.destroy
    end
    redirect_to new_suggestion_path, status: :see_other
  end

  def like
    @suggestion = Suggestion.find(params[:id])
    @suggestion.liked_by current_user
    # redirect_back_or_to index
     
    # content_type is crucial here as it wasn't being received before
    render partial: "suggestion", content_type: "text/html", locals: { s: @suggestion }
  end

  def dislike
    @suggestion = Suggestion.find(params[:id])
    @suggestion.disliked_by current_user
  end

  def description 
    set_suggestion
  end

  def back
    set_suggestion
  end

  def clear
    Suggestion.move_old_weekly_suggestions
    redirect_back_or_to index
  end

  private
  def set_suggestion
    @suggestion = Suggestion.find(params[:id])
  end

  def suggestion_params
    params.require(:suggestion).permit(:movie, :author, :user, :sugg_box_id)
  end

end

app/views/suggestions/_01_04_2024_form.html.erb
<div class="bg-white dark:bg-gray-900">
  <div class="flex justify-center h-screen">
    <div class="hidden bg-repeat bg-moviesug3 lg:block lg:w-2/3">
      <div class="flex items-center h-full px-20 bg-gray-900 bg-opacity-40 ">
        <div>
          <h2 class="text-4xl font-bold text-white">This Week's Suggestions</h2>
          <div class="h-64 overflow-y-scroll">
            <p class="max-w-xl mt-3 text-gray-300">
              <% @sugg_boxes.find_by_name("Weekly").suggestions.each do |s|%>
                <li class="w-full h-10 px-4 py-2 text-white border-b border-gray-200 dark:border-gray-600 bg-gradient-to-r from-teal-500 to-teal-200 rounded-md grid grid-cols-5">
                  <p class="overflow-hidden truncate">
                    <%= s.movie%>
                    <%= button_to "Vote", like_suggestion_path(s.id), {class: "px-5 text-white bg-teal-500 border-0 focus:outline-none hover:bg-teal-600 rounded text-lg"} %>
                    <%= s.votes_for.size%>
                    <% if user_signed_in? %>
                      <% if s.user == current_user.email %>
                        <%= button_to "Delete", suggestion_path(s), form: { data: { turbo_confirm: 'Are you sure?' } } , method: :delete %>
                        <%= button_to "Store", change_box_suggestion_path(s.id)%>
                      <% end %>
                    <% end %>
                  </p>
                </li>
              <% end %>
            </p>
          </div>
          <h2 class="pt-10 text-4xl font-bold text-white">All Time Suggestions</h2>
          <div class="h-64 overflow-y-scroll">
            <p class="max-w-xl mt-3 text-gray-300">
              <% @sugg_boxes.find_by_name("All Encompassing").suggestions.each do |s|%>
                <li class="w-full h-10 px-4 py-2 text-white border-b border-gray-200 dark:border-gray-600 bg-gradient-to-r from-teal-500 to-teal-200 rounded-md grid grid-cols-5">
                  <p class="overflow-hidden truncate">
                    <%= s.movie%>
                    <%= button_to "Vote", like_suggestion_path(s.id), {class: "px-5 text-white bg-teal-500 border-0 focus:outline-none hover:bg-teal-600 rounded text-lg"} %>
                    <%= s.votes_for.size%>
                    <% if user_signed_in? %>
                      <% if s.user == current_user.email %>
                        <%= button_to "Delete", suggestion_path(s), form: { data: { turbo_confirm: 'Are you sure?' } } , method: :delete %>
                      <% end %>
                    <% end %>
                    <%= button_to "Suggest", change_box_suggestion_path(s.id)%>
                  </p>
                </li>
              <% end %>
            </p>
          </div>
          <%= button_to "Move week old suggestions", clear_suggestions_path,{class:"px-5 text-white bg-teal-500 border-0 focus:outline-none hover:bg-teal-600 rounded text-lg" } %>
        </div>
      </div>
    </div>


    <div class="flex items-center w-full max-w-md px-6 mx-auto lg:w-2/6">
      <div class="flex-1">
        <div class="text-center">
          <h2 class="text-4xl font-bold text-center text-gray-700 dark:text-white">Suggestion Box</h2>
          <p class="mt-3 text-gray-500 dark:text-gray-300">Suggest any movie you please, suggestions box reset's weekly on Mondays.</p>
        </div>

        <div class="mt-8">
          <%= form_with model: @suggestion do |form| %>
            <div class="py-2 text-gray-700 dark:text-white">
              <%= form.label "Email (optional)"%><br> 
              <%= form.text_field :user, value:(current_user ? current_user.email : "") , class:"dark:text-black" %>
            </div>

            <div class="py-2 text-gray-700 dark:text-white">
              <%= form.label :suggestion %><br>
              <%= form.text_field :movie, class: "dark:text-black" %>
            </div>

            <div class="py-2 text-gray-700 dark:text-white">
              <%= form.label :your_name %><br>
              <%= form.text_field :author, class: "dark:text-black" %>
            </div>

            <div class="font-bold text-gray-700 dark:text-white"> <%= form.submit %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/suggestions/_edit_form.html.erb
<div class="flex flex-col justify-center h-screen md:flex-row">
  <div class="mt-8">
    <%= form_with model: @suggestion do |form| %>
      <div class="py-2 text-gray-700 dark:text-white">
        <%= form.label "Email (optional)"%><br>
        <%= form.text_field :user, value:(current_user ? current_user.email : "") , class:"dark:text-black" %>
      </div>

      <div class="py-2 text-gray-700 dark:text-white">
        <%= form.label :movie %><br>
        <%= form.text_field :movie, class: "dark:text-black" %>
      </div>

      <div class="py-2 text-gray-700 dark:text-white">
        <%= form.label :your_name %><br>
        <%= form.text_field :author, class: "dark:text-black" %>
      </div>

      <div class="font-bold text-gray-700 dark:text-white"> <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/suggestions/_form.html.erb
<div class="flex flex-col justify-center h-screen md:flex-row">

  <%# suggestions in categories %>
  <div class="bg-repeat bg-moviesug3 lg:block lg:w-2/3">
    <div class="flex items-center h-full px-2 bg-gray-900 pt-60 lg:pt-0 lg:px-20 bg-opacity-40 ">
      <div class="w-full">

        <h2 class="mb-4 text-4xl font-bold text-white">This Week's Suggestions</h2>
        <%= render "suggestions_filtered", suggestions: weekly_suggestions %>

        <div>
          <h2 class="pt-10 mb-4 text-4xl font-bold text-white">All Time Suggestions</h2>
          <%= render "suggestions_filtered", suggestions: all_time_minus_weekly_suggestions %>
        </div>

        <%# reviews form %>
        <div class="pt-4">
          <%= render "reviews/new"%>
        </div>

      </div>
    </div>
  </div>

  <%# suggestion form %>
  <div class="flex items-center w-full max-w-md px-6 mx-auto mt-4 bg-gray-900 lg:w-2/6 md:mt-0 ">
    <div class="flex-1">
      <div class="text-center">
        <h2 class="text-4xl font-bold text-center text-gray-700 dark:text-white">Suggestion Box</h2>
        <p class="mt-3 text-gray-500 dark:text-gray-300">Suggest any movie you please, suggestions box reset's weekly on Mondays.</p>
      </div>

      <div class="mt-8">
        <%= form_with model: @suggestion do |form| %>
          <div class="py-2 text-gray-700 dark:text-white">
            <%= form.label "Email (optional)"%><br>
            <%= form.text_field :user, value:(current_user ? current_user.email : "") , class:"dark:text-black" %>
          </div>

          <div class="py-2 text-gray-700 dark:text-white">
            <%= form.label :suggestion %><br>
            <%= form.text_field :movie, class: "dark:text-black" %>
          </div>

          <div class="py-2 text-gray-700 dark:text-white">
            <%= form.label :your_name %><br>
            <%= form.text_field :author, class: "dark:text-black" %>
          </div>

          <div class="font-bold text-gray-700 dark:text-white"> <%= form.submit %>
          </div>
        <% end %>
      </div>
    </div>

  </div>

app/views/suggestions/_modifiable.html.erb
<h1 class="text-2xl">Just goes to show </h1>
<p><%= s.movie %></p>

app/views/suggestions/_suggestion.erb
<%= turbo_frame_tag s do %> 

  <div data-controller="clip">

    <li class="w-full h-10 px-4 py-2 text-white border-b border-gray-200 dark:border-gray-600 bg-gradient-to-r from-teal-500 to-teal-200 rounded-md grid grid-cols-8">

      <p class="overflow-hidden truncate col-span-2", data-clip-target="source", title="<%= s.description %>"><%= s.movie%></p>
      <%= button_to "Vote", like_suggestion_path(s.id), { class: "px-1 lg:px-5 text-white bg-teal-500 border-0 hover:bg-teal-300 rounded text-lg focus:ring focus:outline-none focus:ring-offset-4 focus:ring-teal-200 focus:ring-opacity-50 active:bg-teal-600 hover:-translate-y-0.5 transition duration-200 bg-teal-500 shadow-lg ", method: :post } %>
      <p class="flex justify-center"><%= s.votes_for.size%></p>
      <%= button_to "Dsc", show_description_suggestion_path(s.id) %>
      <%# <span data-clip-target="source">It's all okay.</span> %>
      <span><%= button_tag "Copy", data: { action: "clip#copy" }, class: "bg-black text-orange-500 rounded-md active:bg-gray-600" %></span>

      <% if user_signed_in? %>
        <% if s.user == current_user.email %>
          <%= button_to "Move", change_box_suggestion_path(s.id), data: { turbo_frame: "_top" } %>
          <%= button_to "Del", suggestion_path(s), form: { data: { turbo_confirm: 'Are you sure?' } } , method: :delete %>
        <% end %>
      <% end %>

    </li>

  </div>

<% end %>

app/views/suggestions/_suggestions_filtered.html.erb
<div class="h-24 overflow-y-scroll scrollbar lg:h-48">
    <% suggestions.each do |s|%>
        <%= render "suggestion", s: s %>
    <% end %>
</div>

app/views/suggestions/back.turbo_stream.erb
<turbo-stream action="replace" target="<%= dom_id(@suggestion) %>">
  <template>
    <%= render @suggestion, s: @suggestion %>
  </template>
</turbo-stream>

<%# replace with self %>
<%# <%= turbo_stream.replace @suggestion, (render 'suggestion', s: @suggestion) %1> %>

app/views/suggestions/description.turbo_stream.erb
<%# <turbo-stream action="replace" target="<%= dom_id(@suggestion) %1>"> %>
<%#   <template> %>
<%#     <turbo_frame id="<%= dom_id(@suggestion) %1>"> %>
<%#       <li class="w-full px-4 py-2 text-white border-b border-gray-200 h-15 grid grid-cols-6 dark:border-gray-600 bg-gradient-to-r from-teal-500 to-teal-400 rounded-md"> %> 
<%#         <p class="col-span-5"> %>
<%#           <%= @suggestion.description %1> %>
<%#         </p> %>
<%#         <%= button_to "Back", back_suggestion_path(@suggestion.id) %1> %>
<%#       </li> %>
<%#     </turbo_frame> %>
<%#   </template> %>
<%# </turbo-stream> %>

<%# replace with self %>
<%# <%= turbo_stream.replace @suggestion, (render 'suggestion', s: @suggestion) %1> %>
<%# <%= turbo_stream.replace @suggestion, (render 'modifiable', s: @suggestion) %1> %>

<%= turbo_stream.replace @suggestion do %>
  <turbo_frame id="<%= dom_id(@suggestion) %>">
  <li class="w-full px-4 py-2 text-white border-b border-gray-200 h-15 grid grid-cols-6 dark:border-gray-600 bg-gradient-to-r from-teal-500 to-teal-400 rounded-md">
    <p class="col-span-5">
      <%= @suggestion.description %>
    </p>
    <%= button_to "Back", back_suggestion_path(@suggestion.id) %>
  </li>
  </turbo_frame>
<% end %>

app/views/suggestions/edit.html.erb
<h1>Edit Suggestion</h1>

<%= render "edit_form", suggestion: @suggestion %>

app/views/suggestions/index.html.erb
<h1>Articles</h1>

<ul>
  <% @suggestions.each do |suggestion| %>
    <li>
      <%= link_to suggestion.movie, suggestion %>
    </li>
  <% end %>
</ul>

app/views/suggestions/new.html.erb
<div class="w-full">
  <div class="sticky top-0">
    <%= render  "shared/nav_bar" %>
  </div>
  <div>
    <%= render "form", suggestion: @suggestion, weekly_suggestions: @weekly_suggestions, all_time_minus_weekly_suggestions: @all_time_minus_weekly_suggestions %>
  </div>
</div>

app/views/suggestions/show.html.erb
<div class="grid grid-cols-1 text-sky-200">
  <div>
    <%= render  "shared/nav_bar" %>
  </div>
  <h1><%= @suggestion.movie %></h1>

  <p><%= @suggestion.author%></p>


  <% if current_user.moderator? %>
    <ul>
      <li> <%= link_to "Edit", edit_suggestion_path(@suggestion)  %></li>
      <li> <%= link_to "Destroy", suggestion_path(@suggestion), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?" }
      %> </li>
    </ul>
  <% end %>
</div>